config/routes.rb
  Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout'}, controllers: { sessions: 'users/sessions' }
  get 'users', to: "users#index"
  get 'users/:id', to: "users#show", as: "user"
  resources :products do
  	resources :comments
  end
  resources :order_items
  resource :cart, only: [:show, :destroy]

  get 'orders/:id', to: "orders#show", as: "order"
  get 'orders', to: "orders#index"
  
  get 'simple_pages/about', to: "simple_pages#about"
  get 'simple_pages/contact', to: "simple_pages#contact"
  post 'simple_pages/thank_you'

  root 'simple_pages#index'

  post 'payments', to: "payments#create"

  mount ActionCable.server => '/cable'
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items

  before_save :update_total

  def calculate_total
    self.order_items.collect { |item| item.product.price * item.quantity }.sum
  end

  def total_item_count
    self.order_items.collect { |item| item.quantity }.sum
  end

  private

  def update_total
    self.total_price = calculate_total
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :authenticate_user!
	load_and_authorize_resource #restricts who can manage orders (abilities defined in ability.rb)

	def index
		@orders = Order.where(user_id: current_user.id)
	end

	def show
		@order = Order.find(params[:id])
	end

end

app/views/orders/index.html.erb
<h1>Your past orders</h1>
<% if @orders.any? %>
  <p>(Click on Order Ref# to view details)</p>
  <div class="row">
    <div class="col-2">
      <strong>Order Ref.</strong>
    </div>
    <div class="col-3">
      <strong>Order Date</strong>
    </div>
    <div class="col-2 text-right">
      <strong># of items</strong>
    </div>
    <div class="col-2 text-right">
      <strong>Status</strong>
    </div>
    <div class="col-2 text-right">
      <strong>Total Price</strong>
    </div>
  </div>
  <% @orders.each do |order| %>
  <div class="row">
    <div class="col-2">
      <%= link_to "berlincoffee-#{order.id}", order_path(order) %>
    </div>
    <div class="col-3">
      <% if order.created_at != nil %>
      <%= order.created_at.strftime(" %d.%m.%Y") %>
      <% end %>
    </div>
    <div class="col-2 text-right">
      <%= order.total_item_count %>
    </div>
    <div class="col-2 text-right">
      <%= order.status %>
    </div>
    <div class="col-2 text-right">
      <%= number_to_euro order.total_price %>
    </div>
  </div>
  <% end %>
<% else %>
  <p>You have no orders yet!</p>
  <%= button_to "Start Shopping", products_path, method: :get,  class: "submit-btn" %>
<% end %>

app/views/orders/show.html.erb
<h1>Order Summary</h1>

<div class="row">
  <div class="col-3 col-md-2">
    <p>Order Ref#:</p>
  </div>
  <div class="col-6 col-md-4">
    <p>berlincoffee-<%= @order.id %></p>
  </div>
</div>
<div class="row">
  <div class="col-3 col-md-2">
    <p>Order Date:</p>
  </div>
  <div class="col-6 col-md-4">
    <% if @order.created_at != nil %>
    <p><%= @order.created_at.strftime(" %d.%m.%Y") %></p>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-3 col-md-2">
    <p>Customer:</p>
  </div>
  <div class="col-6 col-md-4">
    <p><%= @order.user.first_name + " " + @order.user.last_name %></p>
  </div>
</div>
<div class="row">
  <div class="col-3 col-md-2">
    <p>Status:</p>
  </div>
  <div class="col-6 col-md-4">
    <p><%= @order.status %></p>
  </div>
</div>
<div class="row">
  <div class="col-3 col-md-2">
    <p>Total:</p>
  </div>
  <div class="col-6 col-md-4">
    <p><%= number_to_euro @order.total_price %></p>
  </div>
</div>


  <table class="table table-borderless">
    <thead>
      <tr>
        <th scope="col">Img</th>
        <th scope="col">Product</th>
        <th class="text-right" scope="col">Unit Price</th>
        <th scope="col">Quantity</th>
        <th class="text-right" scope="col">Total Price</th>
      </tr>
    </thead>
    <tbody>
      <% @order.order_items.each do |item| %>
      <tr>
        <td>  
          <div class="product-img">
            <%= image_tag(item.product.image_url) %>
          </div>
        </td>
        <td><%= item.product.name %></td>
        <td class="text-right"><%= number_to_euro item.product.price %></td>
        <td><%= item.quantity %></td>
        <td class="text-right"><%= number_to_euro  (item.product.price * item.quantity) %></td>
      </tr>
      <% end %>
      <tr>
        <td class="text-right" colspan="5"><strong><p>Order Total: <%= number_to_euro @order.total_price %></p></strong></td>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <div class="col-sm-6">
      <%= button_to "Continue Shopping", products_path, method: :get,  class: "submit-btn" %>
    </div>
  </div>
  