config/routes.rb
  Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout'}, controllers: { sessions: 'users/sessions' }
  get 'users', to: "users#index"
  get 'users/:id', to: "users#show", as: "user"
  resources :products do
  	resources :comments
  end
  resources :order_items
  resource :cart, only: [:show, :destroy]

  get 'orders/:id', to: "orders#show", as: "order"
  get 'orders', to: "orders#index"
  
  get 'simple_pages/about', to: "simple_pages#about"
  get 'simple_pages/contact', to: "simple_pages#contact"
  post 'simple_pages/thank_you'

  root 'simple_pages#index'

  post 'payments', to: "payments#create"

  mount ActionCable.server => '/cable'
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :order_items
  has_many :products, through: :order_items
  belongs_to :user, required: false
  before_save :update_total
  #before_create :update_status ...(not in use)

  def calculate_total
    self.order_items.collect { |item| item.product.price * item.quantity }.sum
  end

  def items_count
    Rails.cache.fetch([cache_key, __method__]) do
      order_items.count
    end
  end

  private

  # def update_status
  #   if self.status == nil?
  #     self.status = "brewing..."
  #   end
  # end

  def update_total
    self.total_price = calculate_total
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

	def show
		@order_items = current_cart.order_items.order(:created_at)
	end

	def destroy
		current_cart.destroy
		session[:cart_id] = nil
		redirect_to cart_path
	end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<% if @order_items.any? %>
  <table class="table table-borderless">
  	<thead>
    	<tr>
	      <th scope="col">Img</th>
	      <th scope="col">Product</th>
	      <th class="text-right" scope="col">Unit Price</th>
	      <th scope="col">Quantity</th>
	      <th class="text-right" scope="col">Total Price</th>
	      <th scope="col"></th>
	    </tr>
	  </thead>
	  <tbody>
	  	<% @order_items.each do |item| %>
	    <tr>
	      <td>  
	      	<div class="product-img">
    				<%= image_tag(item.product.image_url) %>
  				</div>
  			</td>
	      <td><%= item.product.name %></td>
	      <td class="text-right"><%= number_to_euro item.product.price %></td>
	      <td>
	      	<%= form_for item do |f| %>
	      	<div class="form-inline my-2 my-lg-0">
    				<div class="form-group">
            	<%= f.number_field :quantity, placeholder: item.quantity, class: "form-control form-control-sm ml-sm-2 box-sm" %>
            	<%= f.button '<i class="fas fa-sync" aria-hidden="true"></i>'.html_safe, class: "btn btn-sm no-btn" %>
          	</div>
        	</div>
          <% end %>
        </td>
	      <td class="text-right"><%= number_to_euro  (item.product.price * item.quantity) %></td>
	      <td><%= link_to ('<i class="fas fa-trash-alt"></i>').html_safe, order_item_path(item), :data => {:confirm => "You sure?", :method => "delete"} %></td>
	    </tr>
	    <% end %>
	    <tr>
	    	<td class="text-right" colspan="5"><strong><p>Cart Total: <%= number_to_euro current_cart.total_price %></p></strong></td>
	    </tr>
	    <tr>
	    	<td class="text-right" colspan="5"><%= link_to "Empty Cart", cart_path, :data => {:confirm => "Do you really want to empty your cart?", :method => "delete" } %></td>
	    </tr>
	  </tbody>
	</table>
	<div class="row">
		<div class="col-sm-6">
			<%= button_to "Continue Shopping", products_path, method: :get,  class: "submit-btn" %>
		</div>
		<div class="col-sm-6 text-right">
			<% if user_signed_in? %>
				<%= form_with(url: '/payments') do |f| %>
					<%= f.hidden_field :cart_id, value: current_cart.id %>
  			  <%= render partial: "shared/stripe_checkout_button" %>
  			<% end %>
  		<% else %>
  			<%= button_to 'Login to Checkout Cart', new_user_session_path, method: :get, class: "submit-btn" %>
  		<% end %>
  	</div>
  </div>
<% else %>
<div class="row">
	<div class="col">
		<p>Your shopping cart is empty.</p>
	</div>
</div>
<div class="row text-center">
	<div class="col-4 col-md-2">
		<%= button_to "Start Shopping", products_path, method: :get,  class: "submit-btn" %>
	</div>
	<% if !user_signed_in? %>
	<div class="col-1">
		or
	</div>
	<div class="col-4 col-md-2">
		<%= button_to 'Login to view saved Cart', new_user_session_path, method: :get, class: "submit-btn" %>
	</div>
	<% end %>
</div>
<% end %>