config/routes.rb
  Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout'}, controllers: { sessions: 'users/sessions' }
  get 'users', to: "users#index"
  get 'users/:id', to: "users#show", as: "user"
  resources :products do
  	resources :comments
  end
  resources :order_items
  resource :cart, only: [:show, :destroy]

  get 'orders/:id', to: "orders#show", as: "order"
  get 'orders', to: "orders#index"
  
  get 'simple_pages/about', to: "simple_pages#about"
  get 'simple_pages/contact', to: "simple_pages#contact"
  post 'simple_pages/thank_you'

  root 'simple_pages#index'

  post 'payments', to: "payments#create"

  mount ActionCable.server => '/cable'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new #guest user (not logged in)
    can :read, Product # permissions for every user, even if not logged in
    if user.present?  # additional permissions for logged in users
      can [:create, :destroy], Comment, user_id: user.id
      can [:show, :create, :update, :destroy], User, id: user.id #can manage own user, but can NOT index all users
      can :manage, Order, user_id: user.id
      if user.admin?  # additional permissions for administrators
        can :manage, :all
      end
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :order_items
  has_many :products, through: :order_items
  belongs_to :user, required: false
  before_save :update_total
  #before_create :update_status ...(not in use)

  def calculate_total
    self.order_items.collect { |item| item.product.price * item.quantity }.sum
  end

  def items_count
    Rails.cache.fetch([cache_key, __method__]) do
      order_items.count
    end
  end

  private

  # def update_status
  #   if self.status == nil?
  #     self.status = "brewing..."
  #   end
  # end

  def update_total
    self.total_price = calculate_total
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user

  scope :rating_desc, -> { order(rating: :desc)}

  validates :body, presence: true
  validates :user, presence: true
  validates :product, presence: true
  validates :rating, numericality: {only_integer: true}

  after_create_commit { CommentUpdateJob.perform_later(self, self.user) }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items

  before_save :update_total

  def calculate_total
    self.order_items.collect { |item| item.product.price * item.quantity }.sum
  end

  def total_item_count
    self.order_items.collect { |item| item.quantity }.sum
  end

  private

  def update_total
    self.total_price = calculate_total
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart, touch: true
  belongs_to :order, required: false # needs to be set to false so OrderItem can be first created WITHOUT associating an order

  validates :quantity, numericality: {only_integer: true, greater_than: 0, less_than: 1000}
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items
  has_many :carts, through: :order_items
  has_many :comments, dependent: :destroy

  validates :name, presence: true

  def self.search(search_term)
    Product.where("name ilike ?", "%#{search_term}%")
  end

  def highest_rating_comment
    comments.rating_desc.first
  end

  def lowest_rating_comment
    comments.rating_desc.last
  end

  def average_rating
    comments.average(:rating).to_f
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
  has_many :comments
  has_many :carts 

  after_create :welcome
  def welcome
  	UserMailer.welcome(self).deliver_now
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

	def show
		@order_items = current_cart.order_items.order(:created_at)
	end

	def destroy
		current_cart.destroy
		session[:cart_id] = nil
		redirect_to cart_path
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	load_and_authorize_resource

	def create
		@product = Product.find(params[:product_id])
		@comment = @product.comments.new(comment_params)
		@comment.user = current_user
		@user = current_user
		
		respond_to do |format|
			if @comment.save
				#ActionCable.server.broadcast 'product_channel', comment: @comment, average_rating: @comment.product.average_rating
				#ProductChannel.broadcast_to @product.id, comment: CommentsController.render(partial: 'comments/comment', locals: {comment: @comment, current_user: current_user}), average_rating: @product.average_rating
				format.html { redirect_to @product, notice: 'Review was successfully created.' }
				format.json { render :show, status: :created, location: @product }
				format.js
			else
				format.html { redirect_to @product, alert: 'Oops! Review could not be saved.' }
				format.json { render json: @comment.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@comment = Comment.find(params[:id])
		product = @comment.product
		@comment.destroy

		respond_to do |format|
      format.html { redirect_to product }
      format.json { head :no_content }
      format.js
    end
	end

	private

	def comment_params
		params.require(:comment).permit(:body, :rating, :user_id)
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :authenticate_user!
	load_and_authorize_resource #restricts who can manage orders (abilities defined in ability.rb)

	def index
		@orders = Order.where(user_id: current_user.id)
	end

	def show
		@order = Order.find(params[:id])
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource  

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper

	def cache_key_for_products
		count = @products
		max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
		"products/all-#{count}-#{max_updated_at}"
	end
	
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Berlincoffee</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Roboto:300,300i,500&amp;subset=latin-ext" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
  </head>

  <body>
  
      <nav class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand" href="/">
          <%= image_tag("logo_sm_light.png", class: "img-fluid") %>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "About", simple_pages_about_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "Contact", simple_pages_contact_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "Products", products_path, class: "nav-link" %></li>
          </ul>
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item"><%= link_to 'Hi, ' + current_user.first_name, current_user, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to 'My Orders', orders_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link" %></li>
            <% else %>
            <li class="nav-item"><%= link_to 'Login', new_user_session_path, class: "nav-link" %></li>
            <% end %>
            <li class="nav-item"><%= link_to ('<i class="fas fa-shopping-cart"></i>').html_safe + " (#{current_cart.items_count})", cart_path, class: "nav-link" %></li>
          </ul>
          <%= form_with(url: products_path, method: 'get', local: true, class: "form-inline my-2 my-lg-0") do |f| %>
            <%= f.label :q, "Search for:" %>
            <%= f.text_field :q, id: "q", value: params[:q], class: "form-control mr-sm-2" %>
            <%= f.submit "Search", class: "btn btn-outline-light my-2 my-sm-0"%>
          <% end %>
        </div>
      </nav>
    <div class="main">
      <%= yield :hero %>
      <div class="container">
        <% if notice %>
        <div class="alert alert-dark" role="alert">
          <p class="notice"><%= notice %></p>
        </div>
        <% end %>
        <% if alert %>
        <div class="alert alert-warning" role="alert">
          <p class="alert"><%= alert %></p>
        </div>
        <% end %>
        <%= yield %>
      </div>
    </div><!-- end main -->
    <footer class="container-fluid">
      <ul class="social-buttons">
        <li><a href="#"><i class="fab fa-facebook"></i></a></li>
        <li><a href="#"><i class="fab fa-twitter"></i></a></li>
        <li><a href="#"><i class="fab fa-instagram"></i></a></li>
      </ul>
      <div class="copy">
        <p>&copy; 2018 Berlin Coffee</p>
      </div>
    </footer>
  </body>
</html>

app/views/shared/_stripe_checkout_button.html.erb
<!-- script to be used for product/show page to checkout 1 single product -->
<!-- <script
  src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%#= Rails.configuration.stripe[:publishable_key] %>"
  data-image="/square-image.png"
  data-name="<%#= @product.name %>"
  data-amount="<%#= @product.price * 100 %>">
</script> -->

<!-- script to be used on cart/show page to checkout a whole cart containing multiple items-->
<script
  src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
  data-image="<%= asset_path('logo_sm_dark.png')%>"
  data-name="Berlin Coffee"
  data-description="Your Order"
  data-email="<%= current_user.email %>"
  data-amount="<%= current_cart.total_price * 100 %>"
  data-locale="auto"
  data-currency="eur">
</script>